[versions]
junit-jupiter = "5.10.1"
java = "21"


[libraries]
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
junit-api = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }