
# This workflow will build and publish all submodules declaring use of the "convention-publish-maven" plugin to the GitHub Packages maven repository.

name: Publish to GitHub Packages

on:
  release:
    types: [published]
    
jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Publish package
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew -Pversion=${{ github.ref_name }} publish